# Generated by Django 6.0.6 on 2026-07-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_sold_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sold_count',
            field=models.IntegerField(default=0),
        ),
    ]
